name: SemiTerminal
main: kr.eme.semiTerminal.SemiTerminal
version: 1.0
api-version: 1.20
depend:
  - ProtocolLib
commands:
  terminal:
    description: 터미널 상점을 여는 명령어
    aliases: 상점
    usage: /terminal